<?php
/**
 * Title: Features Home2
 * Slug: corvona/features-home2
 * Categories: corvona pro
 * Keywords: feature-home2
 * @package corvona
 * @since 1.0.0
 */
?>
<!-- wp:group {"metadata":{"categories":["consultica"],"patternName":"consultica/features","name":"Features"},"className":"animated fadeInUp","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|40","right":"var:preset|spacing|40"},"margin":{"top":"0","bottom":"0"}}},"backgroundColor":"assets-nine","layout":{"type":"constrained"}} -->
<div class="wp-block-group animated fadeInUp has-assets-nine-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--40)"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|30","padding":{"top":"0","bottom":"0"}}}} -->
<div class="wp-block-column" style="padding-top:0;padding-bottom:0"><!-- wp:essential-blocks/number-counter {"blockId":"eb-counter-raq8o","blockMeta":{"desktop":".eb-counter-wrapper.eb-counter-raq8o .eb-counter-title,.eb-counter-wrapper.eb-counter-raq8o .eb-counter-number{margin:0;padding:0}.eb-counter-wrapper.eb-counter-raq8o \u003e *{position:relative}.eb-counter-wrapper.eb-counter-raq8o{overflow:hidden;display:flex;flex-direction:column;gap:20px;padding-top:30px;padding-right:10px;padding-left:10px;padding-bottom:30px;background-color:#072D46;transition:background 0.5s,border 0.5s,border-radius 0.5s,box-shadow 0.5s}.eb-counter-wrapper.eb-counter-raq8o .counter-contents-wrapper{display:flex;flex:1;text-align:center;flex-direction:column;gap:4px}.eb-counter-wrapper.eb-counter-raq8o:before{transition:background 0.5s,opacity 0.5s,filter 0.5s}.eb-counter-wrapper.eb-counter-raq8o .eb-counter-number{font-size:32px;font-weight:700;color:#fff}.eb-counter-wrapper.eb-counter-raq8o .eb-counter-title{font-size:16px;font-weight:400;color:#fff}.eb-counter-wrapper.eb-counter-raq8o .eb-counter-prefix{color:var(\u002d\u002deb-global-text-color)}.eb-counter-wrapper.eb-counter-raq8o .eb-counter-suffix{color:#fff}.eb-counter-wrapper.eb-counter-raq8o .icon-img-wrapper{align-self:center;margin-top:0px}.eb-counter-wrapper.eb-counter-raq8o .eb-icon{padding:0px;border-radius:0px}.eb-counter-wrapper.eb-counter-raq8o .eb-icon \u003e *{color:#fff}.eb-counter-wrapper.eb-counter-raq8o .icon-img-wrapper .eb-counter-icon-data-selector{font-size:55px;height:55px;width:55px;display:flex;justify-content:center;align-items:center}","tab":"","mobile":""},"target":"5000","counterSuffix":" +","titleColor":"#fff","numberColor":"#fff","numSuffixColor":"#fff","media":"icon","selectedIcon":"far fa-user","iconColor":"#fff","iconBgColor":"","titleFontSource":"custom","titleFontSize":16,"titleFontWeight":"400","numberFontSource":"custom","numberFontSize":32,"numberFontWeight":"700","suffixFontSource":"global","wrapperMarginTop":"","wrapperMarginRight":"","wrapperMarginBottom":"","wrapperMarginLeft":"","mdBgPdTop":"0","mdBgPdRight":"0","mdBgPdBottom":"0","mdBgPdLeft":"0","mdBgRsisLinked":true,"mdBgRsTop":"0","mdBgRsRight":"0","mdBgRsBottom":"0","mdBgRsLeft":"0","mdBgMgTop":"0","mdBgMgRight":"","mdBgMgBottom":"","mdBgMgLeft":"","wrpBG_backgroundColor":"#072D46","rgNTRange":4,"mIconZRange":55,"commonStyles":{"desktop":".eb-parent-eb-counter-raq8o{display:block}.root-eb-counter-raq8o{position:relative}","tab":".eb-parent-eb-counter-raq8o{display:block}","mobile":".eb-parent-eb-counter-raq8o{display:block}"}} -->
<div class="wp-block-essential-blocks-number-counter  root-eb-counter-raq8o"><div class="eb-parent-wrapper eb-parent-eb-counter-raq8o "><div class="eb-counter-raq8o eb-counter-wrapper"><div class="icon-img-wrapper"><div class="eb-icon "><i icon="far fa-user" class="far fa-user eb-counter-icon-data-selector"></i></div></div><div class="counter-contents-wrapper"><h4 class="eb-counter-number"><span class="eb-counter-prefix"></span><span class="eb-counter eb-counter-number" data-duration="1000" data-startvalue="0" data-target="5000" data-separator="," data-isshowseparator="true">0</span><span class="eb-counter-suffix"> +</span></h4><h3 class="eb-counter-title"><?php echo esc_html__('Active Users', 'corvona'); ?></h3></div></div></div></div>
<!-- /wp:essential-blocks/number-counter --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/number-counter {"blockId":"eb-counter-mm1x8","blockMeta":{"desktop":".eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-title,.eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-number{margin:0;padding:0}.eb-counter-wrapper.eb-counter-mm1x8 \u003e *{position:relative}.eb-counter-wrapper.eb-counter-mm1x8{overflow:hidden;display:flex;flex-direction:column;gap:20px;padding-top:30px;padding-right:10px;padding-left:10px;padding-bottom:30px;background-color:#072D46;transition:background 0.5s,border 0.5s,border-radius 0.5s,box-shadow 0.5s}.eb-counter-wrapper.eb-counter-mm1x8 .counter-contents-wrapper{display:flex;flex:1;text-align:center;flex-direction:column;gap:4px}.eb-counter-wrapper.eb-counter-mm1x8:before{transition:background 0.5s,opacity 0.5s,filter 0.5s}.eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-number{font-size:32px;font-weight:700;color:#fff}.eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-title{font-size:16px;font-weight:400;color:#fff}.eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-prefix{color:var(\u002d\u002deb-global-text-color)}.eb-counter-wrapper.eb-counter-mm1x8 .eb-counter-suffix{color:#fff}.eb-counter-wrapper.eb-counter-mm1x8 .icon-img-wrapper{align-self:center;margin-top:0px}.eb-counter-wrapper.eb-counter-mm1x8 .eb-icon{padding:1px;background-color:#072D46}.eb-counter-wrapper.eb-counter-mm1x8 .eb-icon \u003e *{color:#fff}.eb-counter-wrapper.eb-counter-mm1x8 .icon-img-wrapper .eb-counter-icon-data-selector{font-size:55px;height:55px;width:55px;display:flex;justify-content:center;align-items:center}","tab":"","mobile":""},"target":"1000","counterTitle":"Complete Projects","counterSuffix":" +","titleColor":"#fff","numberColor":"#fff","numSuffixColor":"#fff","media":"icon","selectedIcon":"fab fa-gitlab","iconColor":"#fff","iconBgColor":"#072D46","titleFontSource":"custom","titleFontSize":16,"titleFontWeight":"400","numberFontSource":"custom","numberFontSize":32,"numberFontWeight":"700","suffixFontSource":"global","wrapperMarginTop":"","wrapperMarginRight":"","wrapperMarginBottom":"","wrapperMarginLeft":"","mdBgPdTop":"1","mdBgPdRight":"1","mdBgPdBottom":"1","mdBgPdLeft":"1","mdBgRsTop":"","mdBgRsRight":"","mdBgRsBottom":"","mdBgRsLeft":"","mdBgMgTop":"0","mdBgMgRight":"","mdBgMgBottom":"","mdBgMgLeft":"","wrpBG_backgroundColor":"#072D46","rgNTRange":4,"mIconZRange":55,"commonStyles":{"desktop":".eb-parent-eb-counter-mm1x8{display:block}.root-eb-counter-mm1x8{position:relative}","tab":".eb-parent-eb-counter-mm1x8{display:block}","mobile":".eb-parent-eb-counter-mm1x8{display:block}"}} -->
<div class="wp-block-essential-blocks-number-counter  root-eb-counter-mm1x8"><div class="eb-parent-wrapper eb-parent-eb-counter-mm1x8 "><div class="eb-counter-mm1x8 eb-counter-wrapper"><div class="icon-img-wrapper"><div class="eb-icon "><i icon="fab fa-gitlab" class="fab fa-gitlab eb-counter-icon-data-selector"></i></div></div><div class="counter-contents-wrapper"><h4 class="eb-counter-number"><span class="eb-counter-prefix"></span><span class="eb-counter eb-counter-number" data-duration="1000" data-startvalue="0" data-target="1000" data-separator="," data-isshowseparator="true">0</span><span class="eb-counter-suffix"> +</span></h4><h3 class="eb-counter-title"><?php echo esc_html__('Complete Projects', 'corvona'); ?></h3></div></div></div></div>
<!-- /wp:essential-blocks/number-counter --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/number-counter {"blockId":"eb-counter-w9ala","blockMeta":{"desktop":".eb-counter-wrapper.eb-counter-w9ala .eb-counter-title,.eb-counter-wrapper.eb-counter-w9ala .eb-counter-number{margin:0;padding:0}.eb-counter-wrapper.eb-counter-w9ala \u003e *{position:relative}.eb-counter-wrapper.eb-counter-w9ala{overflow:hidden;display:flex;flex-direction:column;gap:20px;padding-top:30px;padding-right:10px;padding-left:10px;padding-bottom:30px;background-color:#072D46;transition:background 0.5s,border 0.5s,border-radius 0.5s,box-shadow 0.5s}.eb-counter-wrapper.eb-counter-w9ala .counter-contents-wrapper{display:flex;flex:1;text-align:center;flex-direction:column;gap:4px}.eb-counter-wrapper.eb-counter-w9ala:before{transition:background 0.5s,opacity 0.5s,filter 0.5s}.eb-counter-wrapper.eb-counter-w9ala .eb-counter-number{font-size:32px;font-weight:700;color:#fff}.eb-counter-wrapper.eb-counter-w9ala .eb-counter-title{font-size:16px;font-weight:400;color:#fff}.eb-counter-wrapper.eb-counter-w9ala .eb-counter-prefix{color:var(\u002d\u002deb-global-text-color)}.eb-counter-wrapper.eb-counter-w9ala .eb-counter-suffix{color:#fff}.eb-counter-wrapper.eb-counter-w9ala .icon-img-wrapper{align-self:center;margin-top:0px}.eb-counter-wrapper.eb-counter-w9ala .eb-icon{padding:1px;background-color:#072D46}.eb-counter-wrapper.eb-counter-w9ala .eb-icon \u003e *{color:#fff}.eb-counter-wrapper.eb-counter-w9ala .icon-img-wrapper .eb-counter-icon-data-selector{font-size:55px;height:55px;width:55px;display:flex;justify-content:center;align-items:center}","tab":"","mobile":""},"target":"30","duration":"","counterTitle":"Years of Experiene","counterSuffix":" +","titleColor":"#fff","numberColor":"#fff","numSuffixColor":"#fff","media":"icon","selectedIcon":"fab fa-buromobelexperte","iconColor":"#fff","iconBgColor":"#072D46","titleFontSource":"custom","titleFontSize":16,"titleFontWeight":"400","numberFontSource":"custom","numberFontSize":32,"numberFontWeight":"700","suffixFontSource":"global","wrapperMarginTop":"","wrapperMarginRight":"","wrapperMarginBottom":"","wrapperMarginLeft":"","mdBgPdTop":"1","mdBgPdRight":"1","mdBgPdBottom":"1","mdBgPdLeft":"1","mdBgRsTop":"","mdBgRsRight":"","mdBgRsBottom":"","mdBgRsLeft":"","mdBgMgTop":"0","mdBgMgRight":"","mdBgMgBottom":"","mdBgMgLeft":"","wrpBG_backgroundColor":"#072D46","rgNTRange":4,"mIconZRange":55,"commonStyles":{"desktop":".eb-parent-eb-counter-w9ala{display:block}.root-eb-counter-w9ala{position:relative}","tab":".eb-parent-eb-counter-w9ala{display:block}","mobile":".eb-parent-eb-counter-w9ala{display:block}"}} -->
<div class="wp-block-essential-blocks-number-counter  root-eb-counter-w9ala"><div class="eb-parent-wrapper eb-parent-eb-counter-w9ala "><div class="eb-counter-w9ala eb-counter-wrapper"><div class="icon-img-wrapper"><div class="eb-icon "><i icon="fab fa-buromobelexperte" class="fab fa-buromobelexperte eb-counter-icon-data-selector"></i></div></div><div class="counter-contents-wrapper"><h4 class="eb-counter-number"><span class="eb-counter-prefix"></span><span class="eb-counter eb-counter-number" data-duration="0" data-startvalue="0" data-target="30" data-separator="," data-isshowseparator="true">0</span><span class="eb-counter-suffix"> +</span></h4><h3 class="eb-counter-title"><?php echo esc_html__('Years of Experiene', 'corvona'); ?></h3></div></div></div></div>
<!-- /wp:essential-blocks/number-counter --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/number-counter {"blockId":"eb-counter-fb9dn","blockMeta":{"desktop":".eb-counter-wrapper.eb-counter-fb9dn .eb-counter-title,.eb-counter-wrapper.eb-counter-fb9dn .eb-counter-number{margin:0;padding:0}.eb-counter-wrapper.eb-counter-fb9dn \u003e *{position:relative}.eb-counter-wrapper.eb-counter-fb9dn{overflow:hidden;display:flex;flex-direction:column;gap:20px;padding-top:30px;padding-right:10px;padding-left:10px;padding-bottom:30px;background-color:#072D46;transition:background 0.5s,border 0.5s,border-radius 0.5s,box-shadow 0.5s}.eb-counter-wrapper.eb-counter-fb9dn .counter-contents-wrapper{display:flex;flex:1;text-align:center;flex-direction:column;gap:4px}.eb-counter-wrapper.eb-counter-fb9dn:before{transition:background 0.5s,opacity 0.5s,filter 0.5s}.eb-counter-wrapper.eb-counter-fb9dn .eb-counter-number{font-size:32px;font-weight:700;color:#fff}.eb-counter-wrapper.eb-counter-fb9dn .eb-counter-title{font-size:16px;font-weight:400;color:#fff}.eb-counter-wrapper.eb-counter-fb9dn .eb-counter-prefix{color:var(\u002d\u002deb-global-text-color)}.eb-counter-wrapper.eb-counter-fb9dn .eb-counter-suffix{color:#fff}.eb-counter-wrapper.eb-counter-fb9dn .icon-img-wrapper{align-self:center;margin-top:0px}.eb-counter-wrapper.eb-counter-fb9dn .eb-icon{padding:1px;background-color:#072D46}.eb-counter-wrapper.eb-counter-fb9dn .eb-icon \u003e *{color:#fff}.eb-counter-wrapper.eb-counter-fb9dn .icon-img-wrapper .eb-counter-icon-data-selector{font-size:55px;height:55px;width:55px;display:flex;justify-content:center;align-items:center}","tab":"","mobile":""},"target":"45","duration":"30","counterTitle":"Professional Team","counterSuffix":" +","titleColor":"#fff","numberColor":"#fff","numSuffixColor":"#fff","media":"icon","selectedIcon":"fas fa-people-group","iconColor":"#fff","iconBgColor":"#072D46","titleFontSource":"custom","titleFontSize":16,"titleFontWeight":"400","numberFontSource":"custom","numberFontSize":32,"numberFontWeight":"700","suffixFontSource":"global","wrapperMarginTop":"","wrapperMarginRight":"","wrapperMarginBottom":"","wrapperMarginLeft":"","mdBgPdTop":"1","mdBgPdRight":"1","mdBgPdBottom":"1","mdBgPdLeft":"1","mdBgRsTop":"","mdBgRsRight":"","mdBgRsBottom":"","mdBgRsLeft":"","mdBgMgTop":"0","mdBgMgRight":"","mdBgMgBottom":"","mdBgMgLeft":"","wrpBG_backgroundColor":"#072D46","rgNTRange":4,"mIconZRange":55,"commonStyles":{"desktop":".eb-parent-eb-counter-fb9dn{display:block}.root-eb-counter-fb9dn{position:relative}","tab":".eb-parent-eb-counter-fb9dn{display:block}","mobile":".eb-parent-eb-counter-fb9dn{display:block}"}} -->
<div class="wp-block-essential-blocks-number-counter  root-eb-counter-fb9dn"><div class="eb-parent-wrapper eb-parent-eb-counter-fb9dn "><div class="eb-counter-fb9dn eb-counter-wrapper"><div class="icon-img-wrapper"><div class="eb-icon "><i icon="fas fa-people-group" class="fas fa-people-group eb-counter-icon-data-selector"></i></div></div><div class="counter-contents-wrapper"><h4 class="eb-counter-number"><span class="eb-counter-prefix"></span><span class="eb-counter eb-counter-number" data-duration="30" data-startvalue="0" data-target="45" data-separator="," data-isshowseparator="true">0</span><span class="eb-counter-suffix"> +</span></h4><h3 class="eb-counter-title"><?php echo esc_html__('Professional Team', 'corvona'); ?></h3></div></div></div></div>
<!-- /wp:essential-blocks/number-counter --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->