<?php
/**
 * Title: Functions Pro
 * Slug: corvona/functions-pro
 * Categories: corvona pro
 * Keywords: functions-pro
 * @package corvona
 * @since 1.0.0
 */
?>
<!-- wp:group {"className":"animated fadeInUp","style":{"spacing":{"padding":{"top":"var:preset|spacing|2-x-large","bottom":"var:preset|spacing|2-x-large","left":"var:preset|spacing|medium","right":"var:preset|spacing|medium"}},"color":{"gradient":"linear-gradient(157deg,rgb(11,11,24) 39%,rgb(76,75,86) 79%)"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group animated fadeInUp has-background" style="background:linear-gradient(157deg,rgb(11,11,24) 39%,rgb(76,75,86) 79%);padding-top:var(--wp--preset--spacing--2-x-large);padding-right:var(--wp--preset--spacing--medium);padding-bottom:var(--wp--preset--spacing--2-x-large);padding-left:var(--wp--preset--spacing--medium)"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"verticalAlignment":"center","width":"15%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:15%"><!-- wp:group {"className":"overlap-img","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group overlap-img"><!-- wp:image {"id":4759,"width":"75px","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded","style":{"border":{"width":"3px"}},"borderColor":"assets-one"} -->
<figure class="wp-block-image size-full is-resized has-custom-border is-style-rounded"><img src="<?php echo esc_url(get_template_directory_uri()); ?>/assets/images/testimonial-1.jpg" alt="" class="has-border-color has-assets-one-border-color wp-image-4759" style="border-width:3px;width:75px"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":4758,"width":"75px","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded ","style":{"border":{"width":"3px"}},"borderColor":"assets-one"} -->
<figure class="wp-block-image size-full is-resized has-custom-border is-style-rounded"><img src="<?php echo esc_url(get_template_directory_uri()); ?>/assets/images/testimonial-1.jpg" alt="" class="has-border-color has-assets-one-border-color wp-image-4758" style="border-width:3px;width:75px"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":4432,"width":"75px","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded ","style":{"border":{"width":"3px"}},"borderColor":"assets-one"} -->
<figure class="wp-block-image size-full is-resized has-custom-border is-style-rounded"><img src="<?php echo esc_url(get_template_directory_uri()); ?>/assets/images/features.jpg" alt="" class="has-border-color has-assets-one-border-color wp-image-4432" style="border-width:3px;width:75px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-c8akv","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-c8akv{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-line{height:12px;background-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle{width:208px;height:208px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-inner-content{padding:19px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-half{border-width:19px;border-color:rgba(235,224,89,1)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:rgba(235,224,89,1)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-line-fill{height:12px;background-color:rgba(235,224,89,1)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-title{font-size:18px;color:#fff}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-count-wrap{color:#fff}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-inner{border-color:var(\u002d\u002deb-global-background-color);border-width:19px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-half-circle-after{width:208px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-half-circle{width:208px;height:calc(104 * 1px)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-box{height:200px;width:140px;border-width:19px;border-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-box-fill{background-color:rgba(235,224,89,1)}","tab":".eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-half-circle{height:calc(104 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-c8akv .eb-progressbar-half-circle{height:calc(104 * 1px)}"},"layout":"circle","title":"Business Strategy","progress":97,"absoluteProgress":97,"titleColor":"#fff","counterColor":"#fff","progressColor":"rgba(235,224,89,1)","titleTextFontSource":"custom","titleTextFontSize":18,"counterTextFontSource":"global","wrpSizeRange":208,"stkWidthRange":19,"ttlSpaceTop":"","ttlSpaceRight":"","ttlSpaceBottom":"","ttlSpaceLeft":"","commonStyles":{"desktop":".eb-parent-eb-progressbar-c8akv{display:block}.root-eb-progressbar-c8akv{position:relative}","tab":".eb-parent-eb-progressbar-c8akv{display:block}","mobile":".eb-parent-eb-progressbar-c8akv{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-c8akv"><div class="eb-parent-wrapper eb-parent-eb-progressbar-c8akv "><div class="eb-progressbar-wrapper eb-progressbar-c8akv"><div class="eb-progressbar-circle-container center"><div class="eb-progressbar eb-progressbar-circle" data-layout="circle" data-count="97" data-duration="1500" data-type="percentage" data-absolute="97" data-totalrange="100"><div class="eb-progressbar-circle-pie"><div class="eb-progressbar-circle-half-left eb-progressbar-circle-half"></div><div class="eb-progressbar-circle-half-right eb-progressbar-circle-half"></div></div><div class="eb-progressbar-circle-inner"></div><div class="eb-progressbar-circle-inner-content"><div class="eb-progressbar-title"><?php echo esc_html__('Business Strategy', 'corvona'); ?></div><span class="eb-progressbar-count-wrap"><span class="eb-progress-count-wrap"><span class="eb-progressbar-count">97</span><span class="postfix">%</span></span></span></div></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-hrv9u","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-hrv9u{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-line{height:12px;background-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle{width:208px;height:208px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-inner-content{padding:19px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-half{border-width:19px;border-color:rgba(89,148,235,1)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:rgba(89,148,235,1)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-line-fill{height:12px;background-color:rgba(89,148,235,1)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-title{font-size:18px;color:#fff}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-count-wrap{color:#fff}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-inner{border-color:var(\u002d\u002deb-global-background-color);border-width:19px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-half-circle-after{width:208px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-half-circle{width:208px;height:calc(104 * 1px)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-box{height:200px;width:140px;border-width:19px;border-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-box-fill{background-color:rgba(89,148,235,1)}","tab":".eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-half-circle{height:calc(104 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-hrv9u .eb-progressbar-half-circle{height:calc(104 * 1px)}"},"layout":"circle","title":"Growth Plan","progress":90,"absoluteProgress":90,"titleColor":"#fff","counterColor":"#fff","progressColor":"rgba(89,148,235,1)","titleTextFontSource":"custom","titleTextFontSize":18,"counterTextFontSource":"global","wrpSizeRange":208,"stkWidthRange":19,"ttlSpaceTop":"","ttlSpaceRight":"","ttlSpaceBottom":"","ttlSpaceLeft":"","commonStyles":{"desktop":".eb-parent-eb-progressbar-hrv9u{display:block}.root-eb-progressbar-hrv9u{position:relative}","tab":".eb-parent-eb-progressbar-hrv9u{display:block}","mobile":".eb-parent-eb-progressbar-hrv9u{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-hrv9u"><div class="eb-parent-wrapper eb-parent-eb-progressbar-hrv9u "><div class="eb-progressbar-wrapper eb-progressbar-hrv9u"><div class="eb-progressbar-circle-container center"><div class="eb-progressbar eb-progressbar-circle" data-layout="circle" data-count="90" data-duration="1500" data-type="percentage" data-absolute="90" data-totalrange="100"><div class="eb-progressbar-circle-pie"><div class="eb-progressbar-circle-half-left eb-progressbar-circle-half"></div><div class="eb-progressbar-circle-half-right eb-progressbar-circle-half"></div></div><div class="eb-progressbar-circle-inner"></div><div class="eb-progressbar-circle-inner-content"><div class="eb-progressbar-title"><?php echo esc_html__('Growth Plan', 'corvona'); ?></div><span class="eb-progressbar-count-wrap"><span class="eb-progress-count-wrap"><span class="eb-progressbar-count">90</span><span class="postfix">%</span></span></span></div></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-wh4ij","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-wh4ij{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-line{height:12px;background-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle{width:208px;height:208px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-inner-content{padding:19px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-half{border-width:19px;border-color:rgba(235,89,127,1)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:rgba(235,89,127,1)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-line-fill{height:12px;background-color:rgba(235,89,127,1)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-title{font-size:18px;color:#fff}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-count-wrap{color:#fff}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-inner{border-color:var(\u002d\u002deb-global-background-color);border-width:19px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-half-circle-after{width:208px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-half-circle{width:208px;height:calc(104 * 1px)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-box{height:200px;width:140px;border-width:19px;border-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-box-fill{background-color:rgba(235,89,127,1)}","tab":".eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-half-circle{height:calc(104 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-wh4ij .eb-progressbar-half-circle{height:calc(104 * 1px)}"},"layout":"circle","title":"Corporate Vision","progress":92,"absoluteProgress":92,"titleColor":"#fff","counterColor":"#fff","progressColor":"rgba(235,89,127,1)","titleTextFontSource":"custom","titleTextFontSize":18,"counterTextFontSource":"global","wrpSizeRange":208,"stkWidthRange":19,"ttlSpaceTop":"","ttlSpaceRight":"","ttlSpaceBottom":"","ttlSpaceLeft":"","commonStyles":{"desktop":".eb-parent-eb-progressbar-wh4ij{display:block}.root-eb-progressbar-wh4ij{position:relative}","tab":".eb-parent-eb-progressbar-wh4ij{display:block}","mobile":".eb-parent-eb-progressbar-wh4ij{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-wh4ij"><div class="eb-parent-wrapper eb-parent-eb-progressbar-wh4ij "><div class="eb-progressbar-wrapper eb-progressbar-wh4ij"><div class="eb-progressbar-circle-container center"><div class="eb-progressbar eb-progressbar-circle" data-layout="circle" data-count="92" data-duration="1500" data-type="percentage" data-absolute="92" data-totalrange="100"><div class="eb-progressbar-circle-pie"><div class="eb-progressbar-circle-half-left eb-progressbar-circle-half"></div><div class="eb-progressbar-circle-half-right eb-progressbar-circle-half"></div></div><div class="eb-progressbar-circle-inner"></div><div class="eb-progressbar-circle-inner-content"><div class="eb-progressbar-title"><?php echo esc_html__('Corporate Vision', 'corvona'); ?></div><span class="eb-progressbar-count-wrap"><span class="eb-progress-count-wrap"><span class="eb-progressbar-count">92</span><span class="postfix">%</span></span></span></div></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-column"><!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-ex0yy","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-ex0yy{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-line{height:12px;background-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle{width:208px;height:208px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-inner-content{padding:19px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-half{border-width:19px;border-color:rgba(89,235,113,1)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:rgba(89,235,113,1)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-line-fill{height:12px;background-color:rgba(89,235,113,1)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-title{font-size:18px;color:#fff}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-count-wrap{color:#fff}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-inner{border-color:var(\u002d\u002deb-global-background-color);border-width:19px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-half-circle-after{width:208px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-half-circle{width:208px;height:calc(104 * 1px)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-box{height:200px;width:140px;border-width:19px;border-color:var(\u002d\u002deb-global-background-color)}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-box-fill{background-color:rgba(89,235,113,1)}","tab":".eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-half-circle{height:calc(104 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-ex0yy .eb-progressbar-half-circle{height:calc(104 * 1px)}"},"layout":"circle","title":"Strategic Planning","progress":97,"absoluteProgress":97,"titleColor":"#fff","counterColor":"#fff","progressColor":"rgba(89,235,113,1)","titleTextFontSource":"custom","titleTextFontSize":18,"counterTextFontSource":"global","wrpSizeRange":208,"stkWidthRange":19,"ttlSpaceTop":"","ttlSpaceRight":"","ttlSpaceBottom":"","ttlSpaceLeft":"","commonStyles":{"desktop":".eb-parent-eb-progressbar-ex0yy{display:block}.root-eb-progressbar-ex0yy{position:relative}","tab":".eb-parent-eb-progressbar-ex0yy{display:block}","mobile":".eb-parent-eb-progressbar-ex0yy{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-ex0yy"><div class="eb-parent-wrapper eb-parent-eb-progressbar-ex0yy "><div class="eb-progressbar-wrapper eb-progressbar-ex0yy"><div class="eb-progressbar-circle-container center"><div class="eb-progressbar eb-progressbar-circle" data-layout="circle" data-count="97" data-duration="1500" data-type="percentage" data-absolute="97" data-totalrange="100"><div class="eb-progressbar-circle-pie"><div class="eb-progressbar-circle-half-left eb-progressbar-circle-half"></div><div class="eb-progressbar-circle-half-right eb-progressbar-circle-half"></div></div><div class="eb-progressbar-circle-inner"></div><div class="eb-progressbar-circle-inner-content"><div class="eb-progressbar-title"><?php echo esc_html__('Strategic Planning', 'corvona'); ?></div><span class="eb-progressbar-count-wrap"><span class="eb-progress-count-wrap"><span class="eb-progressbar-count">97</span><span class="postfix">%</span></span></span></div></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->